apiVersion: apps/v1
kind: Deployment
metadata:
  name: learning-cms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: learning-cms
  template:
    metadata:
      labels:
        app: learning-cms
    spec:
      containers:
      - name: learning-cms
        image: your-registry/learning-cms:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: learning-cms-service
spec:
  selector:
    app: learning-cms
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer 